config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in:      'login',
                                              sign_out:     'logout',
                                              sign_up: 'register' },
             controllers:        { registrations: 'registrations',
                                   :omniauth_callbacks => "omniauth_callbacks"
                                  }

  devise_for :admins, path: '/admin', path_names: { sign_in: 'login', sign_out: 'logout'},
             controllers: { sessions: 'admin/sessions'},
             :skip => [:registrations]

  authenticated :user do
    root 'users#edit_category', as: :user_root
  end

  authenticated :admin do
    root :path => 'admin', to: 'admin/accounts#index', as: :admin_root
  end

  namespace :admin do
    get '/', :to => 'accounts#index'
    resources :accounts
    resources :posts
    resources :categories
    get :new_schedule, to: 'posts#new_schedule'
    post :create_schedule, to: 'posts#create_schedule'
  end
  resource :users do
    member do
      get :edit_category
      patch :update_category
      get :edit_account
      patch :update_account
      post :set_user_category
      post :store_other_category
    end
  end

  resources :posts, only:[:index]
  resources :accounts, path: 'account', only:[:index] do
  end
  put :update_setting, to: 'accounts#update_setting', as: :update_setting
  post :set_default_profile, to: 'accounts#set_default_profile', as: :set_default_profile

  root 'home#index'

  get 'users/terms-and-conditions' => 'users#terms_and_conditions'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user_licenses = UserLicenseCategory.where(user_id: current_user.id)
    @user_news = UserNewsCategory.where(user_id: current_user.id)
    @user_products = UserProductCategory.where(user_id: current_user.id)
    @user_carriers = UserCarrierCategory.where(user_id: current_user.id)
  end

  def update_setting
    # if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
    #     params[:user].delete(:password)
    #     params[:user].delete(:password_confirmation)
    # end
    if current_user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      sign_in current_user, :bypass => true
      redirect_to accounts_path, notice: 'Your account updated successfully!'
    else
      render "index"
    end
  end

  def set_default_profile
    current_user.default_avatar = params[:avatar_index].to_i
    if current_user.save
      render json: {result: 'success'}, status: :ok
    else
      render json: {error: 'failed'}, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  before_action :authenticate_admin!
  layout 'application_admin'

  def index
    @users = User.order(created_at: :desc)
  end

  def destroy
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.destroy
        format.html { redirect_to admin_accounts_path, notice: 'Removed user successfully!' }
        format.json { render json: admin_accounts_path, status: :created, location: @user }
      else
        format.html { render action: "index", notice: @user.errors }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/admin/accounts/_form.haml
= simple_form_for [:admin, @admin],
  wrapper: :vertical_form,
  wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
  = f.error_notification
  = f.input :email, required: true
  = f.input :first_name
  = f.input :last_name
  = f.input :password, required: true
  = f.input :password_confirmation, required: true

  .hr-line-dashed
  .form-group
    = button_tag(type: 'submit', class: "btn btn-primary") do
      %i.fa.fa-check-circle
      Save  Update

app/views/admin/accounts/_header.slim
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    h2 Manage User Accounts
    ol.breadcrumb
      li
        a href="#"   Home
      li class=((mode == 'index' ? 'active' : '')) 
        = link_to 'Account', admin_accounts_path
      - if mode != 'index'
        li.active
          strong= mode
.result-notice

- if flash[:notice]
  .alert.alert-info.custom-alert-margin.m-t-md
    = flash[:notice]

app/views/admin/accounts/_show.haml
.ibox.float-e-margins
  .ibox-title
    %h5 Manage Users
    = link_to new_admin_company_user_path(@company), :class => 'btn btn-xs btn-primary pull-right' do
      %i.fa.fa-plus
      Add User
  .ibox-content
    %table.table
      %thead
        %tr
          %th Full Name
          %th Email
          %th Added Date
          %th Action
      %tbody
        - @users.each do |user|
          %tr
            %td= user.full_name
            %td= user.email
            %td= user.created_at.to_date
            %td
              = link_to edit_admin_company_user_path(@company, user), :class => 'btn btn-xs btn-warning' do
                %i.fa.fa-edit
                Edit
              = link_to '#', :class => 'btn btn-xs btn-danger' do
                %i.fa.fa-trash-o
                Delete

app/views/admin/accounts/edit.haml
= render 'admin/navbar'
#page-wrapper.gray-bg
  = render 'admin/topbar'
  = render :partial => 'header', :locals => { :mode => 'edit'}
  .row
    .wrapper.wrapper-content.animated.fadeInRight
      = link_to admin_admins_path, :class => 'btn btn-sm btn-info pull-right m-b' do
        %i.fa.fa-long-arrow-left
        Back
      .ibox.float-e-margins
        .ibox-title
          %h5 Edit Admin User
        .ibox-content
          = render :partial => 'form'

app/views/admin/accounts/index.slim
= render 'admin/navbar'
#page-wrapper.gray-bg
  = render 'admin/topbar'
  = render :partial => 'header', :locals => {:mode => 'index'}

  .row
    .wrapper.wrapper-content.animated.fadeInRight
      .ibox.float-e-margins
        .ibox-title
          h5 Manage Users
        .ibox-content
          table.table
            thead
              tr
                th Username
                th Email
                th Added Date
                th Action
            tbody
              - @users.each do |user|
                tr
                  td= user.username
                  td= user.email
                  td= user.created_at.to_date
                  td
                    = link_to admin_account_path(user), method: :delete, :class => 'btn btn-xs btn-danger',
                      data: {confirm: 'Are you sure?'} do
                      i.fa.fa-trash-o
                      |  Delete

app/views/admin/accounts/new.haml
= render 'admin/navbar'
#page-wrapper.gray-bg
  = render 'admin/topbar'
  = render :partial => 'header', :locals => { :mode => 'add'}
  .row
    .wrapper.wrapper-content.animated.fadeInRight
      = link_to admin_admins_path, :class => 'btn btn-sm btn-info pull-right m-b' do
        %i.fa.fa-long-arrow-left
        Back
      .ibox.float-e-margins
        .ibox-title
          %h5 Add Admin User
        .ibox-content
          = render :partial => 'form'