config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in:      'login',
                                              sign_out:     'logout',
                                              sign_up: 'register' },
             controllers:        { registrations: 'registrations',
                                   :omniauth_callbacks => "omniauth_callbacks"
                                  }

  devise_for :admins, path: '/admin', path_names: { sign_in: 'login', sign_out: 'logout'},
             controllers: { sessions: 'admin/sessions'},
             :skip => [:registrations]

  authenticated :user do
    root 'users#edit_category', as: :user_root
  end

  authenticated :admin do
    root :path => 'admin', to: 'admin/accounts#index', as: :admin_root
  end

  namespace :admin do
    get '/', :to => 'accounts#index'
    resources :accounts
    resources :posts
    resources :categories
    get :new_schedule, to: 'posts#new_schedule'
    post :create_schedule, to: 'posts#create_schedule'
  end
  resource :users do
    member do
      get :edit_category
      patch :update_category
      get :edit_account
      patch :update_account
      post :set_user_category
      post :store_other_category
    end
  end

  resources :posts, only:[:index]
  resources :accounts, path: 'account', only:[:index] do
  end
  put :update_setting, to: 'accounts#update_setting', as: :update_setting
  post :set_default_profile, to: 'accounts#set_default_profile', as: :set_default_profile

  root 'home#index'

  get 'users/terms-and-conditions' => 'users#terms_and_conditions'

end

app/views/admin/_navbar.slim
nav.navbar-default.navbar-static-side role="navigation" 
  .sidebar-collapse
    ul#side-menu.nav
      li.nav-header
        .dropdown.profile-element
          span
            = image_tag 'admin/missing.png', :class => 'img-circle'
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            span.clear
              span.block.m-t-xs
                strong.font-bold= current_admin.username
          ul.dropdown-menu.animated.fadeInRight.m-t-xs
            li
              a href="#"   Logout
        .logo-element
          | | IN+
      li class="#{page_class_active 'admin/accounts'}"
        = link_to admin_accounts_path do
          i.fa.fa-user
          span.nav-label Users
      li class="#{page_class_active 'admin/posts'}"
        = link_to admin_posts_path do
          i.fa.fa-comments-o
          span.nav-label Posts
      li class="#{page_class_active 'admin/categories'}"
        = link_to admin_categories_path do
          i.fa.fa-quote-right
          span.nav-label Other Categories

app/views/admin/_topbar.slim
.row.border-bottom
  nav.navbar.navbar-static-top role="navigation"  style="margin-bottom: 0"
    .navbar-header
      a.navbar-minimalize.minimalize-styl-2.btn.btn-primary href="#" 
        i.fa.fa-bars

    ul.nav.navbar-top-links.navbar-right
      li
        = link_to destroy_admin_session_path, :method => :delete do
          i.fa.fa-sign-out Log out