config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in:      'login',
                                              sign_out:     'logout',
                                              sign_up: 'register' },
             controllers:        { registrations: 'registrations',
                                   :omniauth_callbacks => "omniauth_callbacks"
                                  }

  devise_for :admins, path: '/admin', path_names: { sign_in: 'login', sign_out: 'logout'},
             controllers: { sessions: 'admin/sessions'},
             :skip => [:registrations]

  authenticated :user do
    root 'users#edit_category', as: :user_root
  end

  authenticated :admin do
    root :path => 'admin', to: 'admin/accounts#index', as: :admin_root
  end

  namespace :admin do
    get '/', :to => 'accounts#index'
    resources :accounts
    resources :posts
    resources :categories
    get :new_schedule, to: 'posts#new_schedule'
    post :create_schedule, to: 'posts#create_schedule'
  end
  resource :users do
    member do
      get :edit_category
      patch :update_category
      get :edit_account
      patch :update_account
      post :set_user_category
      post :store_other_category
    end
  end

  resources :posts, only:[:index]
  resources :accounts, path: 'account', only:[:index] do
  end
  put :update_setting, to: 'accounts#update_setting', as: :update_setting
  post :set_default_profile, to: 'accounts#set_default_profile', as: :set_default_profile

  root 'home#index'

  get 'users/terms-and-conditions' => 'users#terms_and_conditions'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :carrier_category
  belongs_to :license_category
  belongs_to :news_category
  belongs_to :product_category

  attr_accessor :skip_schedule

  def user_carrier_category
    carrier_category.user_carrier_categories
  end

  def user_license_category
    license_category.user_license_categories
  end

  validates :carrier_category_id, :license_category_id, :news_category_id, :product_category_id, presence: true
  validates :content, length: { in: 2..144 }, presence: true, uniqueness: true
  validates_time :schedule_at, presence: true, on_or_after: DateTime.now, unless: :skip_schedule

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  layout 'application_admin'

  def index
    @posts = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    # users = User.joins(:carrier_categories, :license_categories, :news_categories, :product_categories)
    @post = Post.new(post_params)
    @post.skip_schedule = true

    respond_to do |format|
      if @post.save

        post_to_social_accounts @post

        format.html { redirect_to admin_posts_path, notice: 'Posted Successfully!' }
        format.json { render json: admin_posts_path, status: :created, location: @post }
      else
        format.html { render action: "new", notice: @post.errors }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_schedule
    @post = Post.new
  end

  def create_schedule
    @post = Post.new(schedule_post_params)
    @post.skip_schedule = false

    respond_to do |format|
      if @post.save

        schedule_at = DateTime.new(
            params[:post]["schedule_at(1i)"].to_i,
            params[:post]["schedule_at(2i)"].to_i,
            params[:post]["schedule_at(3i)"].to_i,
            params[:post]["schedule_at(4i)"].to_i,
            params[:post]["schedule_at(5i)"].to_i
        )
        scheduler = Rufus::Scheduler.singleton
        scheduler.at schedule_at.to_s do
        # do something at a given point in time

          post_to_social_accounts @post
        end
        format.html { redirect_to admin_posts_path, notice: 'Posted Successfully!' }
        format.json { render json: admin_posts_path, status: :created, location: @post }
      else
          format.html { render action: "new_schedule", notice: @post.errors }
          format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: 'One Post removed successfully!'
  end
  private

  def post_params
    params.require(:post).permit(:content, :carrier_category_id, :license_category_id, :news_category_id,
                                 :product_category_id, :twitter, :facebook, :linkedin)
  end
  def schedule_post_params
    params.require(:post).permit(:content, :carrier_category_id, :license_category_id, :news_category_id,
                                 :product_category_id, :twitter, :facebook, :linkedin, :schedule_at)
  end

  def post_to_social_accounts post
    # users1 = User.joins(:carrier_categories).where(carrier_categories.id == post.carrier_category_id)
    users = User.joins("left outer JOIN user_carrier_categories ON user_carrier_categories.user_id = users.id")
                .joins("left outer JOIN carrier_categories ON carrier_categories.id = user_carrier_categories.carrier_category_id")
                .joins("left outer JOIN user_license_categories ON user_license_categories.user_id = users.id")
                .joins("left outer JOIN license_categories ON license_categories.id = user_license_categories.license_category_id")
                .joins("left outer JOIN user_news_categories ON user_news_categories.user_id = users.id")
                .joins("left outer JOIN news_categories ON news_categories.id = user_news_categories.news_category_id")
                .joins("left outer JOIN user_product_categories ON user_product_categories.user_id = users.id")
                .joins("left outer JOIN product_categories ON product_categories.id = user_product_categories.product_category_id")
                .where("carrier_categories.id = ? or license_categories.id = ? or news_categories.id = ? or product_categories.id = ?",
                       post.carrier_category_id, post.license_category_id, post.news_category_id, post.product_category_id)
    users.each do |user|
      if post.facebook && user.user_facebook_profile.present?
        begin
          @oauth = Koala::Facebook::OAuth.new(ENV["facebook_app_id"], ENV["facebook_secret"], 'http://localhost:3000')
          @oauth.url_for_oauth_code(:permissions => "publish_stream")
          @auth_token = @oauth.exchange_access_token(user.user_facebook_profile.token)

          @user_graph = Koala::Facebook::API.new(@auth_token)

          user.user_facebook_profile.token = @auth_token
          user.user_facebook_profile.save

          result = @user_graph.put_wall_post(post.content)
        rescue Koala::Facebook::APIError => exc
          logger.error("Problems posting to Facebook Wall..."+self.inspect+" "+exc.message)
        end
      end

      if post.twitter && user.user_twitter_profile.present?
        client = Twitter::REST::Client.new do |config|
          config.consumer_key        = ENV["twitter_api_key"]
          config.consumer_secret     = ENV["twitter_secret"]
          config.access_token        = user.user_twitter_profile.token
          config.access_token_secret = user.user_twitter_profile.secret
        end

        begin
          client.update(post.content)
        rescue Twitter::Error
          logger.error("Twitter says you cannot post same twice")
        rescue Exception
          logger.error("Problems to tweet")
        end
      end

      if post.linkedin && user.user_linkedin_profile.present?
        config = {
            :request_token_path => "/uas/oauth/requestToken?scope=r_basicprofile+w_share",
            :access_token_path  => "/uas/oauth/accessToken",
            :authorize_path     => "/uas/oauth/authorize",
            :api_host           => "https://api.linkedin.com",
            :auth_host          => "https://www.linkedin.com"
        }
        client = LinkedIn::Client.new(ENV["linkedin_app_id"], ENV["linkedin_secret"], config)
        client.authorize_from_access(user.user_linkedin_profile.token, user.user_linkedin_profile.secret)

        begin
          @share_result = client.add_share(:comment => post.content)
        rescue
          @share_result = nil
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @posts = Post.joins("left JOIN carrier_categories ON carrier_categories.id = posts.carrier_category_id")
    #            .joins("left JOIN user_carrier_categories ON user_carrier_categories.carrier_category_id = carrier_categories.id")
    #            .joins("left JOIN license_categories ON license_categories.id = posts.license_category_id")
    #            .joins("left JOIN user_license_categories ON license_categories.id = user_license_categories.license_category_id")
    #            .joins("left JOIN news_categories ON news_categories.id = posts.news_category_id")
    #            .joins("left JOIN user_news_categories ON news_categories.id = user_news_categories.news_category_id")
    #            .joins("left JOIN product_categories ON product_categories.id = posts.product_category_id")
    #            .joins("left JOIN user_product_categories ON product_categories.id = user_product_categories.product_category_id")
    #            .where("user_carrier_categories.user_id = ? or user_license_categories.user_id = ? or user_news_categories.user_id = ? or user_product_categories.user_id = ?",
    #                     current_user.id, current_user.id, current_user.id, current_user.id)

    @posts = Post
               .joins("left JOIN user_carrier_categories ON user_carrier_categories.carrier_category_id = posts.carrier_category_id")
               .joins("left JOIN user_license_categories ON posts.license_category_id = user_license_categories.license_category_id")
               .joins("left JOIN user_news_categories ON posts.news_category_id = user_news_categories.news_category_id")
               .joins("left JOIN user_product_categories ON posts.product_category_id = user_product_categories.product_category_id")
               .where("user_carrier_categories.user_id = ? or user_license_categories.user_id = ? or user_news_categories.user_id = ? or user_product_categories.user_id = ?",
                        current_user.id, current_user.id, current_user.id, current_user.id).distinct
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.slim
= simple_form_for [:admin, @post],
  wrapper: :vertical_form do |f|
  = f.error_notification
  = f.input :content, input_html: { maxlength: 144}, id: 'content_field'
  span#content_count 144 characters
  = f.input :carrier_category_id, collection: CarrierCategory.pluck(:name, :id), as: :select
  = f.input :license_category_id, collection: LicenseCategory.pluck(:name, :id), as: :select
  = f.input :product_category_id, collection: ProductCategory.pluck(:name, :id), as: :select
  = f.input :news_category_id, collection: NewsCategory.pluck(:name, :id), as: :select
  /= select_tag 'user_id', options_for_select(UserFacebookProfile.all.collect{ |u| [u.name, u.id] }), multiple: true, class: 'form-control'
  = f.input :facebook
  = f.input :twitter
  = f.input :linkedin
  .hr-line-dashed
  .form-group
    = button_tag(type: 'submit', class: "btn btn-primary") do
      i.fa.fa-check-circle
      |  Post

app/views/admin/posts/_header.slim
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    h2 Manage Posts
    ol.breadcrumb
      li
        a href="#"   Home
      li class=((mode == 'index' ? 'active' : '')) 
        = link_to 'Posts', admin_posts_path
      - if mode != 'index'
        li.active
          strong= mode
.result-notice

- if flash[:notice]
  .alert.alert-info.custom-alert-margin.m-t-md
    = flash[:notice]

app/views/admin/posts/_schedule_form.slim
= simple_form_for [:admin, @post], url: admin_create_schedule_path,
  wrapper: :vertical_form do |f|
  = f.error_notification
  .row
    .col-md-6
      = f.input :content, input_html: { maxlength: 144}, id: 'content_field'
    .col-md-6
      = f.input :schedule_at
  span#content_count 144 characters
  = f.input :carrier_category_id, collection: CarrierCategory.pluck(:name, :id), as: :select
  = f.input :license_category_id, collection: LicenseCategory.pluck(:name, :id), as: :select
  = f.input :product_category_id, collection: ProductCategory.pluck(:name, :id), as: :select
  = f.input :news_category_id, collection: NewsCategory.pluck(:name, :id), as: :select
  /= select_tag 'user_id', options_for_select(UserFacebookProfile.all.collect{ |u| [u.name, u.id] }), multiple: true, class: 'form-control'
  = f.input :facebook
  = f.input :twitter
  = f.input :linkedin
  .hr-line-dashed
  .form-group
    = button_tag(type: 'submit', class: "btn btn-primary") do
      i.fa.fa-check-circle
      |  Post

app/views/admin/posts/index.slim
= render 'admin/navbar'
#page-wrapper.gray-bg
  = render 'admin/topbar'
  = render :partial => 'header', :locals => {:mode => 'index'}
  .row.m-t-lg
    = link_to new_admin_post_path, :class => 'btn btn-sm btn-info pull-right m-r-sm' do
      i.fa.fa-plus
      |  New Post
    = link_to admin_new_schedule_path, :class => 'btn btn-sm btn-info pull-right m-r-sm' do
      i.fa.fa-tachometer
      |  Schedule Post

  .row
    .wrapper.wrapper-content.animated.fadeInRight
      .ibox.float-e-margins
        .ibox-title
          h5 Manage Posts
        .ibox-content
          table.table
            thead
              tr
                th Content
                th
                  i.fa.fa-facebook
                th
                  i.fa.fa-twitter
                th
                  i.fa.fa-linkedin
                th Schedule At
                th Added Date
                th Action
            tbody
              - @posts.each do |post|
                tr
                  td= truncate(post.content, length: 35)
                  td
                    - if post.facebook
                      i.fa.fa-check-circle.text-navy
                  td
                    - if post.twitter
                      i.fa.fa-check-circle.text-navy
                  td
                    - if post.linkedin
                      i.fa.fa-check-circle.text-navy
                  td= post.schedule_at.blank? ? 'No - Schedule Post' : post.schedule_at.to_s(:long)
                  td= post.created_at.to_date
                  td
                    = link_to admin_post_path(post), method: :delete, :class => 'btn btn-xs btn-danger',
                      data: {confirm: 'Are you sure?'} do
                      i.fa.fa-trash-o
                      |  Delete

app/views/admin/posts/new.slim
= render 'admin/navbar'
#page-wrapper.gray-bg
  = render 'admin/topbar'
  = render :partial => 'header', :locals => {:mode => 'add'}
  .row
    .wrapper.wrapper-content.animated.fadeInRight
      = link_to admin_posts_path, :class => 'btn btn-sm btn-info pull-right m-b' do
        i.fa.fa-long-arrow-left
        |  Back
      .ibox.float-e-margins
        .ibox-title
          h5 New Post
        .ibox-content
          = render 'form'

app/views/admin/posts/new_schedule.slim
= render 'admin/navbar'
#page-wrapper.gray-bg
  = render 'admin/topbar'
  = render :partial => 'header', :locals => {:mode => 'Add Schdule'}
  .row
    .wrapper.wrapper-content.animated.fadeInRight
      = link_to admin_posts_path, :class => 'btn btn-sm btn-info pull-right m-b' do
        i.fa.fa-long-arrow-left
        |  Back
      .ibox.float-e-margins
        .ibox-title
          h5 Schedule Post
        .ibox-content
          = render 'schedule_form'