config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in:      'login',
                                              sign_out:     'logout',
                                              sign_up: 'register' },
             controllers:        { registrations: 'registrations',
                                   :omniauth_callbacks => "omniauth_callbacks"
                                  }

  devise_for :admins, path: '/admin', path_names: { sign_in: 'login', sign_out: 'logout'},
             controllers: { sessions: 'admin/sessions'},
             :skip => [:registrations]

  authenticated :user do
    root 'users#edit_category', as: :user_root
  end

  authenticated :admin do
    root :path => 'admin', to: 'admin/accounts#index', as: :admin_root
  end

  namespace :admin do
    get '/', :to => 'accounts#index'
    resources :accounts
    resources :posts
    resources :categories
    get :new_schedule, to: 'posts#new_schedule'
    post :create_schedule, to: 'posts#create_schedule'
  end
  resource :users do
    member do
      get :edit_category
      patch :update_category
      get :edit_account
      patch :update_account
      post :set_user_category
      post :store_other_category
    end
  end

  resources :posts, only:[:index]
  resources :accounts, path: 'account', only:[:index] do
  end
  put :update_setting, to: 'accounts#update_setting', as: :update_setting
  post :set_default_profile, to: 'accounts#set_default_profile', as: :set_default_profile

  root 'home#index'

  get 'users/terms-and-conditions' => 'users#terms_and_conditions'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user_licenses = UserLicenseCategory.where(user_id: current_user.id)
    @user_news = UserNewsCategory.where(user_id: current_user.id)
    @user_products = UserProductCategory.where(user_id: current_user.id)
    @user_carriers = UserCarrierCategory.where(user_id: current_user.id)
  end

  def update_setting
    # if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
    #     params[:user].delete(:password)
    #     params[:user].delete(:password_confirmation)
    # end
    if current_user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      sign_in current_user, :bypass => true
      redirect_to accounts_path, notice: 'Your account updated successfully!'
    else
      render "index"
    end
  end

  def set_default_profile
    current_user.default_avatar = params[:avatar_index].to_i
    if current_user.save
      render json: {result: 'success'}, status: :ok
    else
      render json: {error: 'failed'}, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  before_action :authenticate_admin!
  layout 'application_admin'

  def index
    @users = User.order(created_at: :desc)
  end

  def destroy
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.destroy
        format.html { redirect_to admin_accounts_path, notice: 'Removed user successfully!' }
        format.json { render json: admin_accounts_path, status: :created, location: @user }
      else
        format.html { render action: "index", notice: @user.errors }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/accounts/_layout.slim
#preloader
  .spinner
.stickem-container
  = render 'layouts/nav'
  .bg-white.wrap-container30-rs.margin-top-30.margin-bottom-30
    .container
      h3.tp-title
        | Your Account
  .container.margin-bottom-50
    = content_tag(:div, flash[:notice], class: 'alert alert-info') if flash[:notice]
    .row
      .col-md-4.col-sm-4
        .profile.animation[data-animation="animation-fade-in-left"]
          h4.profile-title
            | My Profile
          .profile-avatar
            img src="#{get_default_avatar}"
          h4.profile-name
            = current_user.username
          .profile-desc
            a[href="mailto:JohnAgent@agentmail.com"]
              = current_user.email
      .col-md-8.col-sm-8
        .tab-profile.animation[data-animation="animation-fade-in-right"]
          ul.nav.nav-tabs
            li class="#{page_class_active('posts')}"
              = link_to 'My Feed', posts_path
            li class="#{page_class_active('accounts')}"
              = link_to 'My Account', accounts_path
          .tab-content
            = yield

  = render 'layouts/footer'

app/views/accounts/index.slim
= render(layout: 'layout') do
  #my-account.tab-pane.active
    ul.choose-social.row
      - if current_user.user_facebook_profile.present?
        li.col-md-4.col-sm-4 data-avatar-index=1 class="#{avatar_active_class 'facebook'}"
          .block-avatar
            = image_tag current_user.user_facebook_profile.image, class: 'img-responsive profile-image'
          h3.social-name
            | Facebook
      - if current_user.user_twitter_profile.present?
        li.col-md-4.col-sm-4 data-avatar-index=2 class="#{avatar_active_class 'twitter'}"
          .block-avatar
            = image_tag current_user.user_twitter_profile.image, class: 'img-responsive profile-image'
          h3.social-name
            | Twitter
      - if current_user.user_linkedin_profile.present?
        li.col-md-4.col-sm-4 data-avatar-index=3 class="#{avatar_active_class 'linkedin'}"
          .block-avatar
            = image_tag current_user.user_linkedin_profile.image, class: 'img-responsive profile-image'
          h3.social-name
            | Linkedin

    .social-login.margin-bottom50
      - unless current_user.user_facebook_profile.present?
        = link_to content_tag('span', '', class: 'fa fa-facebook') + ' Sign in with Facebook',
                  user_omniauth_authorize_path(:facebook), class: 'btn btn-block btn-social btn-facebook margin-bottom30'
      - unless current_user.user_twitter_profile.present?
        = link_to content_tag('i', '', class: 'fa fa-twitter') + ' Sign in with Twitter',
                  user_omniauth_authorize_path(:twitter), class: 'btn btn-block btn-social btn-twitter margin-bottom30'
      - unless current_user.user_linkedin_profile.present?
        = link_to content_tag('i', '', class: 'fa fa-linkedin') + ' Sign in with LinkedIn',
                  user_omniauth_authorize_path(:linkedin), class: 'btn btn-block btn-social btn-linkedin'

    .change-password

      h4.title
        | Change My Password
      = simple_form_for current_user, wrapper: :vertical_form, method: :put,
        url: update_setting_path do |f|
        .row
          .col-md-8
            = f.input :current_password, label: 'Current Password'
        .row
          .col-md-8
            = f.input :password, label: 'New Password'
        .row
          .col-md-8
            = f.input :password_confirmation, label: 'Confirm New Password'
        = f.input :default_avatar, as: :hidden
        = submit_tag 'Update Password'
    ul.list-comment
      li
        .row
          .col-md-9.col-sm-9
            h4.title
              | Licenses
            .description
              | Life Insurance, Health Insurance, Real Estate
            .user-category
              - @user_licenses.each_with_index do |license, index|
                label= license.license_category.name
                - if index < @user_licenses.length - 1
                  label.margin-right10 ,
          .col-md-3.col-sm-3
            = link_to 'Add/Remove', edit_category_users_path, class: 'btn-custom small'
      li
        .row
          .col-md-9.col-sm-9
            h4.title
              | Products
            .description
              | Life Insurance, Living Benefits Term, Whole Life, Universal/IUL, Medicare Supplement, Indexed Annuities
            .user-category
              - @user_products.each_with_index do |product, index|
                label= product.product_category.name
                - if index < @user_products.length - 1
                  label.margin-right10 ,
          .col-md-3.col-sm-3
            = link_to 'Add/Remove', edit_category_users_path, class: 'btn-custom small'
      li
        .row
          .col-md-9.col-sm-9
            h4.title
              | Carriers
            .description
              | AXA, Baltimore Life, Phoenix, Transamerica, Voya
            .user-category
              - @user_carriers.each_with_index do |carrier, index|
                label= carrier.carrier_category.name
                - if index < @user_carriers.length - 1
                  label.margin-right10 ,
          .col-md-3.col-sm-3
            = link_to 'Add/Remove', edit_category_users_path, class: 'btn-custom small'
      li
        .row
          .col-md-9.col-sm-9
            h4.title
              | News
            .description
              | CNN Money, TIME, Motley Fool, Bloomberg Business, Fox Business, Wall Street Journal, New York Times
            .user-category
              - @user_news.each_with_index do |news, index|
                label= news.news_category.name
                - if index < @user_news.length - 1
                  label.margin-right10 ,
          .col-md-3.col-sm-3
            = link_to 'Add/Remove', edit_category_users_path, class: 'btn-custom small'
      li
        p
          i Placeholder for Stripe Content
        p
          | Need help? Email support at
          strong
            = mail_to "support@orbisdigital.com"
      /li
      /  .row
      /    .col-md-9.col-sm-9
      /      h4.title
      /        | Schedule
      /      .description
      /        | Facebook: Every Couple Weeks
      /        br
      /        | Twitter: Couple Times a Week
      /        br
      /        | LinkedIn: Once a Week
      /    .col-md-3.col-sm-3
      /      a.small.btn-custom[href="#"]
      /        | Add/Remove

#popup-login.mfp-hide.white-popup-block
  h3.margin-bottom50 Connect Your Accounts
  - unless current_user.user_facebook_profile.present?
    = link_to content_tag('span', '', class: 'fa fa-facebook') + ' Sign in with Facebook',
              user_omniauth_authorize_path(:facebook), class: 'btn btn-block btn-social btn-facebook margin-bottom30'
  - unless current_user.user_twitter_profile.present?
    = link_to content_tag('i', '', class: 'fa fa-twitter') + ' Sign in with Twitter',
              user_omniauth_authorize_path(:twitter), class: 'btn btn-block btn-social btn-twitter margin-bottom30'
  - unless current_user.user_linkedin_profile.present?
    = link_to content_tag('i', '', class: 'fa fa-linkedin') + ' Sign in with LinkedIn',
              user_omniauth_authorize_path(:linkedin), class: 'btn btn-block btn-social btn-linkedin'